language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install -U pip setuptools
  - pip install tox-travis

script:
  - tox

notifications:
  email:
    - gback@mitre.org
    - stix-commits-list@lists.mitre.org
