language: python

python:
  - 2.7
 
env:
  - TOXENV=py26-stix111
  - TOXENV=py26-stix120old
  - TOXENV=py26-stix120
  - TOXENV=py27-stix111
  - TOXENV=py27-stix120old
  - TOXENV=py27-stix120

install:
  - pip install -U tox

script:
  - tox

notifications:
  email:
    - gback@mitre.org
    - stix-commits-list@lists.mitre.org
